version: 2

jobs:
  build:
    docker:
      - image: circleci/node:16.4.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install yarn
          command: 'yarn add node-sass'
      - run:
          name: |
          command: npm config set legacy-peer-deps true
     
      - run:
          name: |  
          command: mkdir staticdata
      - run:
          name: submodules
          command: 'git submodule update --init'
      - run:
          name: install
          command: |
            npm install && cd staticdata && git checkout `echo $CIRCLE_BRANCH | sed -e 's/ostap\|chagin/alpha/g'` && git pull && cd .. && ls -la 
      - run:
          name: Installing AWS CLi
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebci --upgrade
      - run: cd ./app && npm install && npm run build
      - run: aws s3 sync ./app/build s3://project-success
          
  workflows:
    version: 2
    execute_bulk: 
      jobs:
      - build:
      
      
