version: 2

jobs:
  build:
    docker:
      - image: circleci/node:16.4.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install yarn
          command: 'yarn add node-sass'
      - run:
          name: |
          command: npm config set legacy-peer-deps true
     
      - run:
          name: |  
          command: mkdir staticdata
      - run:
          name: submodules
          command: 'git submodule update --init'
      - run:
          name: install
          command: |
            npm install && cd staticdata && git checkout `echo $CIRCLE_BRANCH | sed -e 's/ostap\|chagin/alpha/g'` && git pull && cd .. && ls -la 
      - run: 
          name: |
          command: aws s3 sync ./app/build s3://project-success
          
  workflows:
   build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image: # orb built-in job
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update: # orb built-in job
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
      
      
